var verbs = [];
	verbs[0] = ["look", "inspect"];
	verbs[1] = ["use"];
	verbs[2] = ["start", "begin", "play"];
	verbs[3] = ["open"];
	verbs[4] = ["read"];
	verbs[5] = ["go", "move", "walk"];
	verbs[6] = ["get", "grab", "take"];
	verbs[7] = ["exit", "leave"];
	verbs[8] = ["fall", "jump"];
	verbs[9] = ["restart"];
	verbs[10] = ["enter"];
	verbs[11] = ["climb"];
	verbs[12] = ["keep"];
	verbs[13] = ["let"];
	verbs[14] = ["refuse", "decline"]
	verbs[15] = ["accept"]
	verbs[16] = ["let"]